export enum ApplicationEventsEnum {
  ACCEPT_CONNECTION       = 'ACCEPT_CONNECTION',
  CLOSE_CONNECTION        = 'CLOSE_CONNECTION',
  ERROR_CONNECTION        = 'ERROR_CONNECTION',
  ERROR_PACKET_HANDLER    = 'ERROR_PACKET_HANDLER',
  ERROR_PACKET_READER     = 'ERROR_PACKET_READER'
}
